# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmessaging\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0cMessageReply\x12\x0e\n\x06status\x18\x01 \x01(\t2S\n\x0eMessageService\x12\x41\n\x0bSendMessage\x12\x19.messaging.MessageRequest\x1a\x17.messaging.MessageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=28
  _globals['_MESSAGEREQUEST']._serialized_end=61
  _globals['_MESSAGEREPLY']._serialized_start=63
  _globals['_MESSAGEREPLY']._serialized_end=93
  _globals['_MESSAGESERVICE']._serialized_start=95
  _globals['_MESSAGESERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
